name: 🚀 Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🛠 Build the app
        run: npm run build

      - name: 📤 Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: ".next,public,package.json,package-lock.json,next.config.js,data,Utils,app,components,lib,slices,redux,graphql,server.js"
          target: "/var/www/nextjs-app"
          strip_components: 0

      - name: 🚀 Restart app on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            # Install Node.js if not available
            if ! command -v node &> /dev/null; then
              echo "📦 Installing Node.js via nvm..."
              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
              export NVM_DIR="$HOME/.nvm"
              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
              nvm install 18
              nvm use 18
              nvm alias default 18
            fi

            # Reload shell to make sure npm is in path
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Install PM2 if not installed
            if ! command -v pm2 &> /dev/null; then
              echo "📦 Installing PM2..."
              npm install -g pm2
            fi

            cd /var/www/nextjs-app

            # Install prod dependencies
            npm ci --omit=dev

            # Ensure data directory exists
            mkdir -p data
            chmod 755 data
            chmod 644 data/*.json 2>/dev/null || true

            # Restart PM2 app
            if pm2 list | grep -q "nextjs-app"; then
              pm2 stop nextjs-app
              pm2 delete nextjs-app
            fi

            pm2 start npm --name "nextjs-app" -- start
            pm2 save

            echo "✅ Deployment completed successfully!"

      - name: 🔍 Health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            sleep 10

            if ! command -v pm2 &> /dev/null; then
              echo "❌ PM2 not found. Checking fallback on port 3000..."
              if curl -f http://localhost:3000/api/vehicles/status > /dev/null 2>&1; then
                echo "✅ App is responding on port 3000"
              else
                echo "❌ App is not responding on port 3000"
                exit 1
              fi
            else
              if pm2 list | grep -q "nextjs-app.*online"; then
                echo "✅ Application is running successfully with PM2!"
                curl -f http://localhost:3000/api/vehicles/status || echo "⚠️ API not yet responding"
              else
                echo "❌ Application failed to start with PM2"
                pm2 logs nextjs-app --lines 20
                exit 1
              fi
            fi
