name: 🚀 Deploy to Hostinger VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🛠 Build the app
        run: npm run build

      - name: 📤 Copy files to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: ".next,public,package.json,package-lock.json,next.config.js,data,Utils,app,components,lib,slices,redux,graphql,server.js"
          target: "/var/www/nextjs-app"
          strip_components: 0

      - name: 🚀 Restart app on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          script: |
            # Install PM2 globally if not installed
            if ! command -v pm2 &> /dev/null; then
              echo "📦 Installing PM2..."
              npm install -g pm2
            fi
            
            cd /var/www/nextjs-app
            
            # Install production dependencies
            npm ci --omit=dev
            
            # Create data directory if it doesn't exist
            mkdir -p data
            
            # Set proper permissions
            chmod 755 data
            chmod 644 data/*.json 2>/dev/null || true
            
            # Stop existing PM2 process if running
            if pm2 list | grep -q "nextjs-app"; then
              pm2 stop nextjs-app
              pm2 delete nextjs-app
            fi
            
            # Start the application with PM2
            pm2 start npm --name "nextjs-app" -- start
            
            # Save PM2 configuration
            pm2 save
            
            echo "✅ Deployment completed successfully!"

      - name: 🔍 Health check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USER }}
          password: ${{ secrets.HOSTINGER_PASSWORD }}
          script: |
            # Wait a moment for the app to start
            sleep 15
            
            # Check if PM2 is available
            if ! command -v pm2 &> /dev/null; then
              echo "❌ PM2 not found - checking if app is running on port 3000"
              if curl -f http://localhost:3000/api/vehicles/status > /dev/null 2>&1; then
                echo "✅ Application is running on port 3000"
              else
                echo "❌ Application not responding on port 3000"
                exit 1
              fi
            else
              # Check if the app is running with PM2
              if pm2 list | grep -q "nextjs-app.*online"; then
                echo "✅ Application is running successfully with PM2!"
                
                # Test the API endpoint
                curl -f http://localhost:3000/api/vehicles/status || echo "⚠️ API endpoint not responding yet"
              else
                echo "❌ Application failed to start with PM2"
                pm2 logs nextjs-app --lines 20
                exit 1
              fi
            fi
